name = input("Enter your name: ")
email = input("Enter your email: ")
education = input("Enter your education: ")
skills = input("Enter your skills: ")
preferred_roles = input("Enter your preferred job roles: ")
preferred_locations = input("Enter your preferred locations: ")

print("\n--- USER PROFILE ---")
print("Name:", name)
print("Email:", email)
print("Education:", education)
print("Skills:", skills)
print("Preferred Roles:", preferred_roles)
print("Preferred Locations:", preferred_locations)